syntax = "proto3";

package ai.edgez.halow;

enum Operation {
  OPERATION_UNSPECIFIED = 0;
  REQUEST = 1;
  RESPONSE = 2;
  ACKNOWLEDGE = 3;
  BROADCAST = 9;
}

enum Interface {
  INTERFACE_UNSPECIFIED = 0;
  USB = 1;
  BLE = 2;
  WIFI = 3;
  ETHERNET = 4;
  HALOW = 5;
  LORA = 6;
}

enum Mime {
  MIME_UNSPECIFIED = 0;
  MIME_TEXT = 1;
  MIME_VOICE = 2;
  MIME_IMAGE = 3;
  MIME_VIDEO = 4;
  MIME_BINARY = 5;
}

enum MarkerColor {
  MARKER_DEFAULT = 0;
  MARKER_RED = 1;
  MARKER_BLUE = 2;
  MARKER_PURPLE = 3;
  MARKER_YELLOW = 4;
  MARKER_PINK = 5;
  MARKER_BROWN = 6;
  MARKER_GREEN = 7;
  MARKER_ORANGE = 8;
  MARKER_DEEP_PURPLE = 9;
  MARKER_LIGHT_BLUE = 10;
  MARKER_CYAN = 11;
  MARKER_TEAL = 12;
  MARKER_LIME = 13;
  MARKER_DEEP_ORANGE = 14;
  MARKER_GRAY = 15;
  MARKER_BLUE_GRAY = 16;
}

enum DeviceSettingsAction {
  DEVICE_SETTINGS_ACTION_UNSPECIFIED = 0;
  DEVICE_SETTINGS_GET = 1;
  DEVICE_SETTINGS_SET = 2;
  DEVICE_SETTINGS_REPORT = 3;
}

message NetworkPacket {
  uint64 message_id_high = 1;
  uint64 message_id_low = 2;
  uint64 from = 3;
  uint64 to = 4;
  Operation operation = 5;
  Interface interface = 6;
  uint32 sequence = 7;
  uint64 user_high = 8;
  uint64 user_low = 9;
  Mime mime = 10;
  uint32 max_hop = 11;

  oneof body {
    bytes payload = 100;
    string beacon = 101;
    HaLowInterfaceStatus status = 102;
    HaLowInitConfig init = 103;
    DeviceSettings device_settings = 104;
  }
}

message Beacon {
  uint64 user_id_high = 1;
  uint64 user_id_low = 2;
  string user_name = 3;
  bytes user_public_key = 4;
  float attitude = 5;
  float longitude = 6;
  MarkerColor marker = 7;
}

message HaLowInterfaceStatus {
  bool supported = 1;
  bool stack_initialized = 2;
  bool mesh_mode = 3;
  bool link_up = 4;
  bool route_ready = 5;
  bool ready_for_report = 6;
  uint32 ethertype = 7;
  string mesh_id = 8;
  string ip_addr = 9;
  string gateway = 10;
  uint64 mac_address = 11;
}

message HaLowInitConfig {
  string country_code = 1;
  string mesh_id = 2;
  string passphrase = 3;
  uint32 max_hop = 4;
  uint64 user_id_high = 5;
  uint64 user_id_low = 6;
  string user_name = 7;
  bytes user_public_key = 8;
}

message DeviceSettings {
  DeviceSettingsAction action = 1;
  bool device_mode_enabled = 2;
  string mesh_id = 3;
  bool share_location = 4;
  string user_name = 5;
  MarkerColor marker = 6;
  uint32 beacon_interval_seconds = 7;
  uint64 user_id_high = 8;
  uint64 user_id_low = 9;
  bytes user_public_key = 10;
  bytes user_private_key = 11;
  float latitude = 12;
  float longitude = 13;
  uint32 max_hop = 14;
}
